apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.auth.appName }}
spec:
  type: {{ .Values.auth.service.type }}
  ports:
    - port: {{ .Values.auth.service.port }}
      targetPort: {{ .Values.auth.service.targetPort }}
      protocol: TCP
  selector:
    {{- toYaml .Values.auth.selectorLabels | nindent 4 }}
