# Default values for tasks-demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
auth:
  appName: auth

  selectorLabels:
    app: auth

  replicaCount: 1

  image:
    repository: honeyo7/kub-demo-auth
    # Overrides the image tag whose default is the chart appVersion.
    tag: latest

  service:
    type: ClusterIP
    port: 80
    targetPort: 80

  resources: 
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 128Mi

  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 3
    targetCPUUtilizationPercentage: 60
    targetMemoryAverageValue: 150Mi

  livenessProbe:
    enabled: true
    path: /auth/check
    port: 80
    initialDelaySeconds: 20
    periodSeconds: 10

  readinessProbe:
    enabled: true
    path: /auth/check
    port: 80
    initialDelaySeconds: 50
    periodSeconds: 10

users:
  appName: users

  selectorLabels:
    app: users

  replicaCount: 1

  image:
    repository: honeyo7/kub-demo-users
    # Overrides the image tag whose default is the chart appVersion.
    tag: latest

  service:
    type: NodePort
    port: 8080
    targetPort: 8080

  resources: 
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 128Mi

  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 3
    targetCPUUtilizationPercentage: 60
    targetMemoryAverageValue: 150Mi

  livenessProbe:
    enabled: true
    path: /users/check
    port: 8080
    initialDelaySeconds: 20
    periodSeconds: 10

  readinessProbe:
    enabled: true
    path: /users/check
    port: 8080
    initialDelaySeconds: 50
    periodSeconds: 10

tasks:
  appName: tasks

  selectorLabels:
    app: tasks

  replicaCount: 1

  image:
    repository: honeyo7/kub-demo-tasks
    # Overrides the image tag whose default is the chart appVersion.
    tag: latest
    env:
      - name: AUTH_ADDRESS
        value: "auth.default"
      - name: TASKS_FOLDER
        value: tasks

  service:
    type: NodePort
    port: 8000
    targetPort: 8000

  resources: 
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 128Mi

  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 3
    targetCPUUtilizationPercentage: 60
    targetMemoryAverageValue: 150Mi

  livenessProbe:
    enabled: true
    path: /tasks/check
    port: 8000
    initialDelaySeconds: 20
    periodSeconds: 10

  readinessProbe:
    enabled: true
    path: /tasks/check
    port: 8000
    initialDelaySeconds: 50
    periodSeconds: 10

  volumeEfs:
    enabled: true
    persistentVolumeClaimName: tasks-pvc
    persistentVolumeName: tasks-pv
    accessModes:
      - ReadWriteMany
    storage: 1Gi
    volumeHandle: fs-0c095fd5cfe0d4f80
    volumeName: tasks-volume
    mountPath: /app/tasks

ingress:
  enabled: true
  className: "alb"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  hosts:
    - host: 
      paths:
        - path: /tasks/
          pathType: Prefix
          serviceName: tasks
          servicePort: 8000
        - path: /signup/
          pathType: Prefix
          serviceName: users
          servicePort: 8080
        - path: /login/
          pathType: Prefix
          serviceName: users
          servicePort: 8080
        - path: /users/
          pathType: Prefix
          serviceName: users
          servicePort: 8080

serviceAccount:
    # Specifies whether a service account should be created
  create: false
    # Annotations to add to the service account
  annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
  name: ""

nameOverride: ""
fullnameOverride: ""
